### ISSUE TITLE
Civic Clerk scrapers

### ISSUE THREAD

**Issue by fgregg** [datamade/civic-scraper#16]
Sites

- [ ] https://www.charlottesville.gov/1077/Agendas-Minutes
- [ ] https://donaanacounty.org/dac-meeting-agendas/civic-clerk-agenda
- [ ] https://chaffeecoco.civicclerk.com/web/home.aspx

Find a few more examples by searching "Civic Clerk" in google

**Comment by fatima3558** [comment]
https://mineralwellstx.civicclerk.com/web/home.aspx

https://indianolaia.civicclerk.com/web/home.aspx

https://alpharettaga.civicclerk.com/web/home.aspx

https://northstpaulmn.civicclerk.com/web/home.aspx
